name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # - name: multiple command
    #   uses: appleboy/ssh-action@v0.1.10
    #   with:
    #       host: '18.167.36.15'
    #       username: 'ec2-user'
    #       key: ${{ secrets.SSH_KEY }}
    #       port: '22'
    #       script: |
    #         whoami
    #         ls -al
    #多主机发布
    - name: multiple host
      uses: appleboy/ssh-action@v0.1.10
      with:
         host: "18.167.36.15,18.162.148.217"
         sync: true
         username: 'ec2-user'
         key: ${{ secrets.KEY }}
         port: '22'
         script: |
           whoami
           ls -al